/*******************************************************************************
 * Copyright (c) 2026 Obeo.
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Obeo - initial API and implementation
 ******************************************************************************/
package pepper.peppermm.provider.spec;

import java.util.Collection;

import org.eclipse.emf.common.notify.AdapterFactory;

import pepper.domain.services.TaskComputationService;
import pepper.peppermm.AbstractTask;
import pepper.peppermm.PepperPackage;
import pepper.peppermm.Task;
import pepper.peppermm.provider.AbstractTaskItemProvider;

/** Customization of the item provider implementation generated by EMF. */
public class AbstractTaskItemProviderSpec extends AbstractTaskItemProvider {
    public AbstractTaskItemProviderSpec(AdapterFactory adapterFactory) {
        super(adapterFactory);
    }

    @Override
    protected void collectNewChildDescriptors(Collection<Object> newChildDescriptors, Object object) {

        if (object instanceof AbstractTask abstractTask) {
            Task task = new TaskComputationService().createNewTask(abstractTask, getString("_UI_New") + " " + getString("_UI_Task_type"));

            newChildDescriptors.add(this.createChildParameter(PepperPackage.Literals.ABSTRACT_TASK__SUB_TASKS, task));
        }
    }

}
