/*******************************************************************************
 * Copyright (c) 2026 Obeo.
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Obeo - initial API and implementation
 ******************************************************************************/
package pepper.peppermm.provider.spec;

import java.util.Collection;

import org.eclipse.emf.common.notify.AdapterFactory;

import pepper.domain.services.WorkpackageComputationService;
import pepper.peppermm.PepperFactory;
import pepper.peppermm.PepperPackage;
import pepper.peppermm.Project;
import pepper.peppermm.Workpackage;
import pepper.peppermm.provider.ProjectItemProvider;

/** Customization of the item provider implementation generated by EMF. */
public class ProjectItemProviderSpec extends ProjectItemProvider {
    public ProjectItemProviderSpec(AdapterFactory adapterFactory) {
        super(adapterFactory);
    }

    @Override
    public Object getImage(Object object) {
        return overlayImage(object, this.getClass().getClassLoader().getResource("icons/full/obj16/Project.svg"));
    }

    @Override
    protected void collectNewChildDescriptors(Collection<Object> newChildDescriptors, Object object) {
        if (object instanceof Project project) {
            String name = getString("_UI_New") + " " + getString("_UI_Workpackage_type");
            Workpackage workpackage = new WorkpackageComputationService().createNewWorkpackage(project, name);

            newChildDescriptors.add(this.createChildParameter(PepperPackage.Literals.PROJECT__OWNED_WORKPACKAGES, workpackage));
        }

        newChildDescriptors.add(this.createChildParameter(PepperPackage.Literals.PROJECT__OWNED_OBJECTIVES, PepperFactory.eINSTANCE.createObjective()));

        newChildDescriptors.add(this.createChildParameter(PepperPackage.Literals.PROJECT__OWNED_TAG_FOLDERS, PepperFactory.eINSTANCE.createTagFolder()));

        newChildDescriptors.add(this.createChildParameter(PepperPackage.Literals.PROJECT__OWNED_RISKS, PepperFactory.eINSTANCE.createRisk()));
    }

}
