/*******************************************************************************
 * Copyright (c) 2026 Obeo.
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Obeo - initial API and implementation
 ******************************************************************************/
package pepper.peppermm.provider.spec;

import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.Collection;
import java.util.Optional;

import org.eclipse.emf.common.notify.AdapterFactory;

import pepper.peppermm.PepperFactory;
import pepper.peppermm.PepperPackage;
import pepper.peppermm.Project;
import pepper.peppermm.Workpackage;
import pepper.peppermm.provider.ProjectItemProvider;

/** Customization of the item provider implementation generated by EMF. */
public class ProjectItemProviderSpec extends ProjectItemProvider {
    public ProjectItemProviderSpec(AdapterFactory adapterFactory) {
        super(adapterFactory);
    }

    @Override
    public Object getImage(Object object) {
        return overlayImage(object, this.getClass().getClassLoader().getResource("icons/full/obj16/Project.svg"));
    }

    @Override
    protected void collectNewChildDescriptors(Collection<Object> newChildDescriptors, Object object) {
        super.collectNewChildDescriptors(newChildDescriptors, object);

        Workpackage workpackage = PepperFactory.eINSTANCE.createWorkpackage();
        workpackage.setName(getString("_UI_New") + " " + getString("_UI_Workpackage_type"));
        if (object instanceof Project project) {

            Optional<Workpackage> optionalWorkpackage = project.getOwnedWorkpackages().stream().reduce((first, second) -> second)
                    .filter(filteredWorkpackage -> filteredWorkpackage.getEndDate() != null && filteredWorkpackage.getStartDate() != null);
            if (optionalWorkpackage.isPresent()) {
                Workpackage lastWorkpackage = optionalWorkpackage.get();
                workpackage.setStartDate(lastWorkpackage.getEndDate().plusDays(1));
                long difference = lastWorkpackage.getStartDate().until(lastWorkpackage.getEndDate(), ChronoUnit.DAYS);
                workpackage.setEndDate(lastWorkpackage.getEndDate().plusDays(difference + 1));
            } else {
                LocalDate endDate = null;
                if (project.getEffectiveEndDate() != null) {
                    endDate = project.getEffectiveEndDate();
                } else if (project.getContractualEndDate() != null) {
                    endDate = project.getContractualEndDate();
                }
                LocalDate startDate = null;
                if (project.getEffectiveStartDate() != null) {
                    startDate = project.getEffectiveStartDate();
                } else if (project.getContractualStartDate() != null) {
                    startDate = project.getContractualStartDate();
                }
                if (startDate != null && endDate != null) {
                    workpackage.setStartDate(startDate);
                    workpackage.setEndDate(endDate);
                }
            }
        }

        newChildDescriptors.add(this.createChildParameter(PepperPackage.Literals.PROJECT__OWNED_WORKPACKAGES, workpackage));

        newChildDescriptors.add(this.createChildParameter(PepperPackage.Literals.PROJECT__OWNED_OBJECTIVES, PepperFactory.eINSTANCE.createObjective()));

        newChildDescriptors.add(this.createChildParameter(PepperPackage.Literals.PROJECT__OWNED_TAG_FOLDERS, PepperFactory.eINSTANCE.createTagFolder()));

        newChildDescriptors.add(this.createChildParameter(PepperPackage.Literals.PROJECT__OWNED_RISKS, PepperFactory.eINSTANCE.createRisk()));
    }

}
