/*******************************************************************************
 * Copyright (c) 2026 Obeo.
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Obeo - initial API and implementation
 ******************************************************************************/
package pepper.peppermm.provider.spec;

import java.util.Collection;

import org.eclipse.emf.common.notify.AdapterFactory;

import pepper.peppermm.PepperFactory;
import pepper.peppermm.PepperPackage;
import pepper.peppermm.provider.ResourceFolderItemProvider;

/** Customization of the item provider implementation generated by EMF. */
public class ResourceFolderItemProviderSpec extends ResourceFolderItemProvider {
    public ResourceFolderItemProviderSpec(AdapterFactory adapterFactory) {
        super(adapterFactory);
    }

    @Override
    public Object getImage(Object object) {
        return overlayImage(object, this.getClass().getClassLoader().getResource("icons/full/obj16/ResourceFolder.svg"));
    }

    @Override
    protected void collectNewChildDescriptors(Collection<Object> newChildDescriptors, Object object) {
        super.collectNewChildDescriptors(newChildDescriptors, object);

        newChildDescriptors.add(this.createChildParameter(PepperPackage.Literals.RESOURCE_FOLDER__OWNED_RESOURCES, PepperFactory.eINSTANCE.createPerson()));

        newChildDescriptors.add(this.createChildParameter(PepperPackage.Literals.RESOURCE_FOLDER__OWNED_RESOURCES, PepperFactory.eINSTANCE.createTeam()));

        newChildDescriptors.add(this.createChildParameter(PepperPackage.Literals.RESOURCE_FOLDER__OWNED_RESOURCES, PepperFactory.eINSTANCE.createInternalStakeholder()));

        newChildDescriptors.add(this.createChildParameter(PepperPackage.Literals.RESOURCE_FOLDER__OWNED_RESOURCES, PepperFactory.eINSTANCE.createExternalStakeholder()));

        newChildDescriptors.add(this.createChildParameter(PepperPackage.Literals.RESOURCE_FOLDER__SUB_FOLDERS, PepperFactory.eINSTANCE.createResourceFolder()));
    }

}
