/*******************************************************************************
 * Copyright (c) 2026 Obeo.
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Obeo - initial API and implementation
 ******************************************************************************/
package pepper.peppermm.provider.spec;

import java.util.Collection;

import org.eclipse.emf.common.notify.AdapterFactory;

import pepper.peppermm.provider.TaskItemProvider;

/**
 * Customization of the item provider implementation generated by EMF.
 * @author lfasani
 */
public class TaskItemProviderSpec extends TaskItemProvider {
    public TaskItemProviderSpec(AdapterFactory adapterFactory) {
        super(adapterFactory);
    }

    @Override
    public Object getImage(Object object) {
        return this.overlayImage(object, this.getClass().getClassLoader().getResource("icons/full/obj16/Task.svg"));
    }

    @Override
    protected void collectNewChildDescriptors(Collection<Object> newChildDescriptors, Object object) {
        new AbstractTaskItemProviderSpec(this.getAdapterFactory()).collectNewChildDescriptors(newChildDescriptors, object);
    }

}
