/**
 * Copyright (c) 2024, 2026 CEA LIST and Others.
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 * 
 * Contributors:
 *     Obeo - initial API and implementation
 */
package pepper.peppermm.provider.spec;

import java.util.Collection;

import org.eclipse.emf.common.notify.AdapterFactory;

import pepper.peppermm.provider.TaskMilestoneItemProvider;

/**
 * Customization of the item provider implementation generated by EMF.
 * @author lfasani
 */
public class TaskMilestoneItemProviderSpec extends TaskMilestoneItemProvider {
	public TaskMilestoneItemProviderSpec(AdapterFactory adapterFactory) {
		super(adapterFactory);
	}

	@Override
	protected void collectNewChildDescriptors(Collection<Object> newChildDescriptors, Object object) {
		//nothing can be created from a milestone
	}

	@Override
	public Object getImage(Object object) {
		return this.overlayImage(object, this.getClass().getClassLoader().getResource("icons/full/obj16/TaskMilestone.svg"));
	}
}
