/*******************************************************************************
 * Copyright (c) 2026 Obeo.
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Obeo - initial API and implementation
 ******************************************************************************/
package pepper.peppermm.provider.spec;

import java.time.Instant;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.time.temporal.ChronoUnit;
import java.util.Collection;
import java.util.Optional;

import org.eclipse.emf.common.notify.AdapterFactory;

import pepper.peppermm.PepperFactory;
import pepper.peppermm.PepperPackage;
import pepper.peppermm.Task;
import pepper.peppermm.Workpackage;
import pepper.peppermm.provider.WorkpackageItemProvider;

/** Customization of the item provider implementation generated by EMF. */
public class WorkpackageItemProviderSpec extends WorkpackageItemProvider {
    public WorkpackageItemProviderSpec(AdapterFactory adapterFactory) {
        super(adapterFactory);
    }

    @Override
    public Object getImage(Object object) {
        return overlayImage(object, this.getClass().getClassLoader().getResource("icons/full/obj16/Workpackage.svg"));
    }

    @Override
    protected void collectNewChildDescriptors(Collection<Object> newChildDescriptors, Object object) {
        super.collectNewChildDescriptors(newChildDescriptors, object);

        Task task = PepperFactory.eINSTANCE.createTask();
        task.setName(getString("_UI_New") + " " + getString("_UI_Task_type"));
        if (object instanceof Workpackage workpackage) {
            Optional<Task> optionalTask = workpackage.getOwnedTasks().stream().reduce((first, second) -> second)
                    .filter(filteredTask -> filteredTask.getEndTime() != null && filteredTask.getStartTime() != null);

            if (optionalTask.isPresent()) {
                Task lastTask = optionalTask.get();
                if (lastTask.getEndTime().equals(lastTask.getStartTime())) {
                    // If the last task is a Milestone
                    task.setStartTime(lastTask.getEndTime());
                    task.setEndTime(lastTask.getEndTime());
                } else {
                    task.setStartTime(lastTask.getEndTime().plus(1, ChronoUnit.MINUTES));
                    task.setEndTime(Instant.ofEpochSecond(2 * lastTask.getEndTime().getEpochSecond() - lastTask.getStartTime().getEpochSecond()).plus(1, ChronoUnit.MINUTES));
                }
            } else {
                if (workpackage.getEndDate() != null && workpackage.getStartDate() != null) {
                    ZonedDateTime zdt = workpackage.getStartDate().atStartOfDay(ZoneId.systemDefault());
                    String zone = zdt.getOffset().toString();
                    String startTime = workpackage.getStartDate().toString() + "T00:00:00.00" + zone;
                    String endTime = workpackage.getEndDate().toString() + "T23:59:00.00" + zone;
                    Instant startInstant = Instant.parse(startTime);
                    Instant endInstant = Instant.parse(endTime);
                    task.setStartTime(startInstant);
                    task.setEndTime(endInstant);
                }
            }
        }

        newChildDescriptors.add(this.createChildParameter(PepperPackage.Literals.WORKPACKAGE__OWNED_TASKS, task));

        newChildDescriptors.add(this.createChildParameter(PepperPackage.Literals.WORKPACKAGE__OUTPUTS, PepperFactory.eINSTANCE.createWorkpackageArtefact()));

        newChildDescriptors.add(this.createChildParameter(PepperPackage.Literals.WORKPACKAGE__OWNED_OBJECTIVES, PepperFactory.eINSTANCE.createObjective()));
    }

}
