/*******************************************************************************
 * Copyright (c) 2026 Obeo.
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Obeo - initial API and implementation
 ******************************************************************************/
package pepper.peppermm.provider.spec;

import java.util.Collection;

import org.eclipse.emf.common.notify.AdapterFactory;

import pepper.domain.services.TaskComputationService;
import pepper.peppermm.PepperFactory;
import pepper.peppermm.PepperPackage;
import pepper.peppermm.Task;
import pepper.peppermm.TaskMilestone;
import pepper.peppermm.Workpackage;
import pepper.peppermm.provider.WorkpackageItemProvider;

/** Customization of the item provider implementation generated by EMF. */
public class WorkpackageItemProviderSpec extends WorkpackageItemProvider {
    public WorkpackageItemProviderSpec(AdapterFactory adapterFactory) {
        super(adapterFactory);
    }

    @Override
    public Object getImage(Object object) {
        return this.overlayImage(object, this.getClass().getClassLoader().getResource("icons/full/obj16/Workpackage.svg"));
    }

    @Override
    protected void collectNewChildDescriptors(Collection<Object> newChildDescriptors, Object object) {
        if (object instanceof Workpackage workpackage) {
            Task task = new TaskComputationService().createNewTask(workpackage, this.getString("_UI_New") + " " + this.getString("_UI_Task_type"));
            newChildDescriptors.add(this.createChildParameter(PepperPackage.Literals.WORKPACKAGE__OWNED_TASKS, task));

            TaskMilestone milestone = new TaskComputationService().createNewMilestone(workpackage, this.getString("_UI_New") + " " + this.getString("_UI_TaskMilestone_type"));
            newChildDescriptors.add(this.createChildParameter(PepperPackage.Literals.WORKPACKAGE__OWNED_TASKS, milestone));
        }

        newChildDescriptors.add(this.createChildParameter(PepperPackage.Literals.WORKPACKAGE__OUTPUTS, PepperFactory.eINSTANCE.createWorkpackageArtefact()));

        newChildDescriptors.add(this.createChildParameter(PepperPackage.Literals.WORKPACKAGE__OWNED_OBJECTIVES, PepperFactory.eINSTANCE.createObjective()));
    }

}
